# Generated by Django 3.1 on 2020-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('post_text', models.CharField(max_length=600)),
                ('post_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
